### ISSUE TITLE
TMI setup

### ISSUE THREAD

**Issue by srivarra** [angelolab/tmi#5]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

**Section 1: Design details**

**Relevant background**

The purpose of **tmi** is to host a suite of tools and processes utilized by [ark-analysis](https://github.com/angelolab/ark-analysis), [toffy](https://github.com/angelolab/toffy), and [mibi-bin-tools](https://github.com/angelolab/mibi-bin-tools). In addition it attempts to solve the following issues:
   1. Utilizing one file for all package requirements, split into two sections (for now), main *dependencies* and *development dependencies*.
   2. Poetry allows us to develop, test, and build for multiple versions of Python in a straightforward manor.
   3. **It is now *easy* to build for different versions of Python, on different operating systems, on different hardware architectures**
   4. As an aside, **[Python's Dependency Hell is somewhat solved](https://xkcd.com/1987/)**

**Design overview**

The main components of the proposed project:

1. `pyproject.toml` is where the majority of the setup is housed. This is the *new* `setuptools`.
Each section is headed with `[tool.<...>]`, where `<...>` is a specific Python tool utilized.
2. `.pre-commit-config.yaml` is file which executes [`pre-commit`](https://pre-commit.com), running *Git Hooks* in order to identify basic issues before submitting code. (i.e. formatting). This runs on *every* commit. If errors are detected, they are fixed, and the developer must add the changes and run `git commit` again.

**Design list/flowchart**

```sh
tmi/
├── .travis.yml # The file for running CI on Travis, it also builds the package
├── .pre-commit-config.yaml # The file which runs on commit, auto-formats according to PEP8
├── .flake8 # Contains various settings for flake8 in `.pre-commit-config.yaml`
├── .pytest_cache/ # pytest cache
├── LICENSE # Modified Apache 2.0 License
├── README.md # Project information
├── __pycache__/ # python cache
├── conftest.py # Used by pytest, also adds utility testing functions to the path
├── poetry.lock # A file containing every package used in the project, all versions are frozen here. Assures that everyone uses the same versions of the dependencies needed. (from us, to Travis-CI)
├── pyproject.toml # A monolithic file containing all build information, dependencies, and preferences for formatting, coverage, and testing
├── src # Contains tmi, the source repo
│   └── tmi # Contains all utility functions
│       ├── __init__.py # Always need an empty __init__.py
│       ├── __pycache__/ # python cache
│       ├── misc_utils.py # The first file added
│       └── py.typed # file for type annotations, PEP-561
├── tests # Contains all tests, and test utility functions
│   ├── __init__.py # Always need an empty __init__.py
│   ├── __pycache__/ # python cache
│   ├── misc_utils_test.py # Tests misc_utils.py
│   └── utils # Testing utility folder
│       ├── __init__.py # Always need an empty __init__.py
│       └── utils.py # Testing utility file
└── tox.ini # Some dev-dependencies do not support the pyproject.toml format (i.e. pycodestyle)
```

**Required inputs**

All tests go in `tests/`, and all code is housed in `src/tmi/`.

**Output files**

N/A

**Section 2: Implementation details**

**File Details**

1. `pyproject.toml`
   1. **[tool.poetry.dependencies]:** Package dependencies needed to run the scripts in `tmi`. (`tmi` is built with these.)
   2. **[tool.poetry.dev-dependencies]:** Package dependencies needed to develop, test and format `tmi`. (not included when `tmi` is built.)
   3. **[build-system]:** Utilizes Poetry's build system.
   4. The other sections reference preferences for tools such as `pytest` for testing, `black` for formatting, etc...
2. `.pre-commit-config.yaml`
   1. Contains commands executed by `pre-commit` for auto-formatting, and styleguide checking.
   2. There are a ton of these, so I only included a few basic formatting hooks. If there are any others that are interesting and helpful that you may come across, feel free to add to it!

**Tools**

**[Poetry](https://python-poetry.org)** makes dependency management and building Python packages very easy.
1. It will always create an isolated virtualenv to install packages into. It doesn't pollute any environment you currently have.
2. **(Optional)** I use *[pyenv](https://github.com/pyenv/pyenv)* as a Python version manager to organize python versions and create virtual environments. There are a lot of version managers, so just pick your poison.
3. **[pre-commit](https://pre-commit.com)** is used for formatting *on-commit*.

**Control flow**

### Setup Instructions

**Assumptions**
1. Python is installed one way or another, either with a version manager or whatever other method.

**Installation of the new stuff**
1. [Install Poetry](https://python-poetry.org/docs/#installation)
   1. Note, WSL2 is highly recommended if you are on Windows.
   2. Install with: (Linux, WSL2)

         ```sh
         curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
         ``` 
         OR (macOS)
         ```sh
         brew install poetry
         ```
   3. Check that it is installed correctly by running `poetry --version` in your terminal.
2. Clone [angelolab/tmi](https://github.com/angelolab/tmi)
   1. `cd` into it.
   2. To make sure that Poetry is picking up all the settings in `pyproject.toml` run:
 
        ```sh
        poetry show --tree
        ```
        This will list all the dependencies and development dependencies.
    3. Now we can install all the packages with their respective versions and extras in `poetry.lock` with 

        ```sh
        poetry install
        ```
    4. Refer to the [documentation](https://python-poetry.org/docs/cli/) for detailed information for each command available
    5. You can run pytest with:

        ```sh
        poetry run pytest
        ```
    6. The `run` command executes the proceeding command inside the project's virtual environment.
    7. We can install and run all the pre-commit hooks via:

        ```sh
        poetry run pre-commit install
        ```

        ```sh
        poetry run pre-commit run --all-files
        ```

**Milestones and timeline**

Next, all utility functions in `ark-analysis` need to be moved over into `tmi`.

**Comment by ngreenwald** [comment]
This is awesome, super thorough and helpful description of everything. 

Can you provide a few more details about the pre-commit hooks? Does this mean that every commit has to pass whatever linter/pycodestyle conventions we're enforcing? Or just you'll get warned if it doesn't?

**Comment by srivarra** [comment]
Every commit has to pass the linter/pycodestyle conventions. If it does not, the `pre-commit` step fixes all of them (directly modifies the files) and will not allow you to commit. The changed files are then unstaged and must be add in again.

For example, say we run `git add some_module1.py some_module2.py some_module3.py` and `git commit -m "made a module"`. Lets say that `some_module1.py` isn't formatted correctly and looks like the code block below:

```python
from tmi.misc_utils import create_invalid_data_str
from tmi.misc_utils import verify_in_list
from tmi.misc_utils import verify_same_elements
```

`pre-commit` will run through each of the git hooks, and because of the git hook `isort`, it will fail.

`isort` will now fix the formatting of `some_module1.py` by reformatting the python imports to:

```python
from tmi.misc_utils import create_invalid_data_str, verify_in_list, verify_same_elements
```

This change is now unstaged (can check with `git status`). Next we would need to re-stage the changes by `git add some_module.py`, and re-run `git commit -m "module isort formatting". It will then run through each git hook, and make sure it follows the conventions. Sometimes, `pre-commit` won't run a git hook because the result from the previous commit was cached, and no changes were made to that file.

Now all the changes will be committed, and the user can push to their branch.

**Comment by ngreenwald** [comment]
Okay cool. Personally, I think the pre-commit checking is probably overkill for our purposes. Given that this stuff all gets checked with pytest, I think this adds another layer of complexity without a clear benefit. 

I think one of the reasons people use stuff like this is so that long builds don't fail due to formatting errors, which I don't see as a major concern for us. Is there another reason that this is useful? Otherwise, I'd say save the template for how to set it up but leave it out for now
